---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.0
spec:
  releaseName: echo-prod
  chart:
    git: git@github.com:nirfuchs73/helm-operator-get-started
    path: charts/echo
    ref: master
  values:
    image:
      repository: nirfuchs73/echo
      tag: 1.0.9
    replicaCount: 1
