---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.0
spec:
  releaseName: echo-prod
  chart:
    git: git@github.com:nirfuchs73/helm-operator-get-started
    path: charts/echo
    ref: master
  values:
    image:
      repository: nirfuchs73/echo
      tag: 1.0.10
    replicaCount: 1
    mongodb:
      port: "3000"
      loglevel: info
      persist: "true"
      dbname: "echo"
      mongodburl: bW9uZ29kYjovL2VjaG91c2VyOnBhc3N3b3JkMTIzQG1vbmdvZGIuZGI6MjcwMTcvZWNobwo=
