---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: podinfo-prod
  chart:
    git: git@github.com:nirfuchs73/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: nirfuchs73/podinfo
      tag: 0.4.11
    replicaCount: 3
