{{ if eq .Values.mongodb.persist "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo
data:
  PORT: "{{ .Values.mongodb.port }}"
  LOGLEVEL: "{{ .Values.mongodb.loglevel }}"
  PERSIST: "{{ .Values.mongodb.persist }}"
  DBNAME: "{{ .Values.mongodb.dbname }}"
{{ end }}