apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
          ports:
            - containerPort: 3000
          # {{ if eq .Values.mongodb.persist "true" }}
          envFrom:
            - configMapRef:
                name: echo
            - secretRef:
                name: mongo-uri
          # {{ end }}
            