{{ if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-test-ingress
  annotations:
    nginx.org/proxy-connect-timeout: "900s"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  {{ range $host := .Values.ingress.hosts }}
  - host: {{ $host.host }}
  {{ end }}
    http:
      paths:
      - backend:
          serviceName: echo-cluster-ip-service
          servicePort: 80
{{ end }}
