---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:staging-*
spec:
  releaseName: echo-rc
  chart:
    git: git@github.com:nirfuchs73/helm-operator-get-started
    path: charts/echo
    ref: master
  values:
    image:
      repository: nirfuchs73/echo
      tag: staging-0b702d4
    replicaCount: 1
    mongodb:
      port: "3000"
      loglevel: info
      persist: "true"
      dbname: "echo-staging"
      mongodburl: bW9uZ29kYjovL2VjaG91c2VyOnBhc3N3b3JkMTIzQG1vbmdvZGIuZGI6MjcwMTcvZWNoby1zdGFnaW5nCg==
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
