---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: echo-rc
  chart:
    git: git@github.com:nirfuchs73/helm-operator-get-started
    path: charts/echo
    ref: master
  values:
    image:
      repository: eu.gcr.io/lustrous-setup-267010/echo
      tag: 1.0.4
    replicaCount: 1
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
