---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:staging-*
spec:
  releaseName: echo-rc
  chart:
    git: git@github.com:nirfuchs73/helm-operator-get-started
    path: charts/echo
    ref: master
  values:
    image:
      repository: nirfuchs73/echo
      tag: staging-7af7701
    replicaCount: 1
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
